# Worflow for the CMake project. Without documentation.
# Saves a lot of time, as LaTeX installation is not needed.
name: Ubuntu 24.04 no Tex doc full test

on:
  push:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - name: Install root and Thermus dependencies
      run: sudo apt install -y nlohmann-json3-dev liburing-dev libgsl-dev libvdt-dev libtbb-dev
    - name: Create root dir
      run: mkdir ../root
    - name: Download root
      run: cd ../root/ && wget -q https://root.cern/download/root_v6.32.06.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
    - name: Unpack root
      run: cd ../root/ && tar -axf root_v6.32.06.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
    - name: Set SYSROOT
      run: cd ../root/ && echo "SYSROOT="`pwd`"/root" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Inplace build
      run: source $SYSROOT/bin/thisroot.sh && ${{github.workspace}}/scripts/inplace_build.sh -DWITHOUT_TEX_DOC=ON

    - name: Inplace test
      run: source $SYSROOT/bin/thisroot.sh && ${{github.workspace}}/local/share/doc/Thermus/tests/inplace_test.sh ${{github.workspace}}/run_thermus 

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

