# Worflow for the CMake project. Without documentation.
# Saves a lot of time, as LaTeX installation is not needed.
name: Macos 15 no Tex doc full test
on:
  push:
  
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-15

    steps:
    - name: Install root
      run:
        brew install root

    - uses: actions/checkout@v4

    - name: Inplace build
      run: ${{github.workspace}}/scripts/inplace_build.sh -DWITHOUT_TEX_DOC=ON

    - name: Inplace test
      run: ${{github.workspace}}/local/share/doc/Thermus/tests/inplace_test.sh ${{github.workspace}}/run_thermus
    
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
