name: Lint

on:
  push:
    branches: ["dev4ywork3"]

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
#permissions:
#  checks: read
#  contents: read

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Install your linters here

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
